export const FETCH_SINGLE_APARTMENT = "FETCH_SINGLE_APARTMENT";
export const FETCH_SINGLE_APARTMENT_ERROR = "FETCH_SINGLE_APARTMENT_ERROR";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";